receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
processors:
extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    size_mib: 512
exporters:
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true
  logging:
    loglevel: debug
  #prometheus:
  #  endpoint: 0.0.0.0:8889
  #  namespace: "testapp"
service:
  extensions: [health_check,pprof,zpages,memory_ballast]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger]
    #metrics:
    #  receivers: [otlp]
    #  processors: []
    #  exporters: [prometheus, logging]