receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
processors:
extensions:
  health_check: {}
exporters:
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    insecure: true
  #prometheus:
  #  endpoint: 0.0.0.0:8889
  #  namespace: "testapp"
  logging:
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger]
    #metrics:
    #  receivers: [otlp]
    #  processors: []
    #  exporters: [prometheus, logging]