version: "2"
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   #UI
      - "6831"
      - "6832"
      - "14268"
      - "14269"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.54.0
    ports:
      - "4317" # Default endpoint for otlp receiver.
      - "8889"  # Default endpoint for querying metrics.
      #- "1888"
      #- "8888"
      #- "13133"
      #- "55670"
    command:
      - "/otelcol"
      - "--config=/conf/otel-collector-config.yaml"
    volumes:
      - ./docker-config:/conf

  demo-server:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      - OTEL_COLLECTOR_ENDPOINT=otel-collector:4317
    command: ["sleep", "36000"]
    ports:
      - "7080"
    volumes:
      - ./src:/app
      - ./docker-config:/conf